### ISSUE TITLE
Fatal color returns warn color

### ISSUE THREAD

**Issue by tsuz** [kz/discordrus#3]
When I set the fatal color, it seems to use warn color.
```
func init() {
...
EnableCustomColors: true,      
CustomLevelColors: &discordrus.LevelColors{
	Debug: 10170623,
	Info:  3581519,
	Warn:  14913035,
	Error: 12651008,
	Panic: 12651008,
	Fatal: 12651008,
},
...
}

func main() {
	log.Error("Hi")
	log.Fatal("Hi")
}
```
<img width="243" alt="0030-05-10 10 46 26" src="https://user-images.githubusercontent.com/6927131/39848011-91cec7f0-543f-11e8-8ca1-d42de25e6063.png">

It seems like [this code](https://github.com/kz/discordrus/blob/33686bb2fcab3f6c65d3393d985b0841b067fc59/levels.go#L33-L48) is causing the issue. 

Is this currently being worked on? If not, I can make a PR.

**Comment by kz** [comment]
Hi, thanks for catching this! It's definitely still being worked on. I'll take a look later today.

**Comment by kz** [comment]
Hi @tsuz. Unfortunately I'm too busy revising for exams tomorrow so I won't be able to get on an IDE. Do you mind making a PR for this? Otherwise I'll get around to fixing this over the weekend.

**Comment by tsuz** [comment]
@kz No problem, I made a [PR](https://github.com/kz/discordrus/pull/4) here so let me know if there's an issue. I also found another bug with custom levels so that's also in the same PR.

**Comment by kz** [comment]
Tests are passing. Thanks for your contribution!
