### ISSUE TITLE
New Trace log level in logrus

### ISSUE THREAD

**Issue by dgsb** [kz/discordrus#5]
Hello, I'm just opening this issue to let you know, the next release of logrus (v1.2.0) will add a new trace level named Trace below Debug.
Here is the PR for reference sirupsen/logrus#844
You may want to take into account this new level.

**Comment by kz** [comment]
Many thanks for letting me know! I will implement this over the coming weeks.

**Comment by kz** [comment]
Apologies for the delay; it's been a busy academic year for me. I've implemented the trace log level now!

**Comment by kz** [comment]
Closed by #7.
