### ISSUE TITLE
Failed to fire hook: Post : unsupported protocol scheme ""

### ISSUE THREAD

**Issue by GAZ082** [kz/discordrus#6]
Hey. I'm just testing this with my app and using the demo config i get subject's error.

**Comment by kz** [comment]
Hi, thanks for letting me know. I'll have to investigate this over the next fortnight and get back to you. Pull requests are always welcome!

**Comment by kz** [comment]
Hi, apologies for the delayed response; it's been a busy few months for me!

This error occurs when the webhook URL is invalid. Are you sure you have set the `DISCORDRUS_WEBHOOK_URL` environment variable correctly? The webhook URL should be in the format, `https://discordapp.com/api/webhooks/***/***`.
