### ISSUE TITLE
Question about usage

### ISSUE THREAD

**Issue by MostHated** [kz/discordrus#8]
Hey there,
This is definitely something I will be using, looks great. I was wondering if it also had the ability to take all standard console logs generated by Discordgo and output them through logrus as well? I am not to the point of setting up much within discord itself yet, I would really like to have all current logs go through logrus though.

Thanks,
-MH

**Comment by kz** [comment]
Hi, thanks for your question! I haven't used Discordgo before so I can't answer this question unfortunately. Given logrus' main driver is to send output to the console, I don't imagine there is a way to redirect console output back into logrus. That said, please let me know if you find out any ways to do so!
